export const AuthActionTypes = {
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',

  GET_LADY_HEALTH_WORKER_PATIENTS_START:
    'GET_LADY_HEALTH_WORKER_PATIENTS_START',
  GET_LADY_HEALTH_WORKER_PATIENTS_SUCCESS:
    'GET_LADY_HEALTH_WORKER_PATIENTS_SUCCESS',
  GET_LADY_HEALTH_WORKER_PATIENTS_FAIL: 'GET_LADY_HEALTH_WORKER_PATIENTS_FAIL',

  GET_SESSIONS_LIST_START: 'GET_SESSIONS_LIST_START',
  GET_SESSIONS_LIST_SUCCESS: 'GET_SESSIONS_LIST_SUCCESS',
  GET_SESSIONS_LIST_FAIL: 'GET_SESSIONS_LIST_FAIL',

  GET_SESSION_DETAILS_START: 'GET_SESSION_DETAILS_START',
  GET_SESSION_DETAILS_SUCCESS: 'GET_SESSION_DETAILS_SUCCESS',
  GET_SESSION_DETAILS_FAIL: 'GET_SESSION_DETAILS_FAIL',

  GET_ASSESSMENT_DETAILS_START: 'GET_ASSESSMENT_DETAILS_START',
  GET_ASSESSMENT_DETAILS_SUCCESS: 'GET_ASSESSMENT_DETAILS_SUCCESS',
  GET_ASSESSMENT_DETAILS_FAIL: 'GET_ASSESSMENT_DETAILS_FAIL',

  SUBMIT_ASSESSMENT_START: 'SUBMIT_ASSESSMENT_START',
  SUBMIT_ASSESSMENT_SUCCESS: 'SUBMIT_ASSESSMENT_SUCCESS',
  SUBMIT_ASSESSMENT_FAIL: 'SUBMIT_ASSESSMENT_FAIL',

  SUBMIT_SESSION_START: 'SUBMIT_SESSION_START',
  SUBMIT_SESSION_SUCCESS: 'SUBMIT_SESSION_SUCCESS',
  SUBMIT_SESSION_FAIL: 'SUBMIT_SESSION_FAIL',

  SET_SELECTED_PATIENT: 'SET_SELECTED_PATIENT',
  LOGOUT_USER: 'LOGOUT_USER',
  START_RECORDING: 'START_RECORDING',
};
