export const icons = {
  logo: require('./icons/logo.png'),
  logout: require('./icons/logout.png'),
  search: require('./icons/search.png'),
  dashboard: require('./icons/dashboard.png'),
  play: require('./icons/play.png'),
  pause: require('./icons/pause.png'),
  typing: require('./icons/typing.png'),
  delete: require('./icons/delete.png'),
  'user-placeholder': require('./icons/user-placeholder.png'),
  'assesment-title': require('./icons/assesment-title.png'),
  'start-record': require('./icons/start-record.png'),
  'stop-record': require('./icons/stop-record.png'),
  'back-arrow': require('./icons/back-arrow.png'),
  'down-arrow': require('./icons/down-arrow.png'),
  'lady-worker': require('./icons/lady-worker.png'),
  'post-placeholder': require('./icons/post-placeholder.png'),
  'right-arrow': require('./icons/right-arrow.png'),
  'session-five': require('./icons/session-five.png'),
  'session-four': require('./icons/session-four.png'),
  'session-one': require('./icons/session-one.png'),
  'session-three': require('./icons/session-three.png'),
  'session-title': require('./icons/session-title.png'),
  'session-two': require('./icons/session-two.png'),
};
